version: '3.3'
services:
  nginx:
    image: swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/ecommerce-vue-app:v1.0.0@sha256:e3dc2cda9840980d34187c49c41308bd441ad90f270be2a1b90a87295876b4bc
    restart: always
    ports:
      - "41730:41730"
