## spark session
app_name: 'CTR Demo DIN'
local: False
worker_count: 2
server_count: 2
worker_cpu: 2
server_cpu: 2
batch_size: 256
worker_memory: '10G'
server_memory: '10G'
coordinator_memory: '10G'

## datasets
train_path: ${MY_S3_BUCKET}/movielens/25m/rank-seq/train.parquet
test_path: ${MY_S3_BUCKET}/movielens/25m/rank-seq/test.parquet

## model configurations
din_column_name_path: ${MY_S3_BUCKET}/movielens/25m/rank-seq/column_schema_din_25M.txt
din_combine_schema_path: ${MY_S3_BUCKET}/movielens/25m/rank-seq/combine_schema_din_25M.txt
wide_column_name_path: ${MY_S3_BUCKET}/movielens/25m/rank-seq/column_schema_din_25M.txt
wide_combine_schema_path: ${MY_S3_BUCKET}/movielens/25m/rank-seq/combine_schema_wide.txt
deep_column_name_path: ${MY_S3_BUCKET}/movielens/25m/rank-seq/column_schema_din_25M.txt
deep_combine_schema_path: ${MY_S3_BUCKET}/movielens/25m/rank-seq/combine_schema_deep.txt

model_in_path: null
model_out_path: ${MY_S3_BUCKET}/movielens/model/din/model_out/ml_1m/
model_export_path: null
model_version: '0.1'
experiment_name: movie_lens_din_1m
input_label_column_index: 0
metric_update_interval: 100

## model hyper params
use_wide: False
use_deep: False
din_embedding_dim: 32
wide_embedding_dim: 32
deep_embedding_dim: 32
din_attention_hidden_layers: [16, 8]
din_attention_hidden_activations: dice
din_attention_batch_norm: True
din_attention_dropout: 0.1
din_hidden_layers: [32, 16]
din_hidden_activations: dice
din_hidden_batch_norm: True
din_hidden_dropout: 0.25
din_seq_column_index_list: [1]
din_target_column_index_list: [2]
deep_hidden_units: [32, 16]
deep_hidden_activations: ReLU
deep_hidden_dropout: 0.2
deep_hidden_batch_norm: True
sparse_init_var: 0.01
ftrl_l1: 1.0
ftrl_l2: 120.0
ftrl_alpha: 0.5
ftrl_beta: 1.0
adam_learning_rate: 0.0001
train_epoches: 1