## spark session
app_name: 'CTR Demo DIN'
local: True
worker_count: 1
server_count: 1
worker_cpu: 1
server_cpu: 1
batch_size: 1000
worker_memory: '5G'
server_memory: '5G'
coordinator_memory: '5G'

## datasets
train_path: s3://dmetasoul-bucket/xwb/demo/movielens/1m/rank/train.parquet
test_path: s3://dmetasoul-bucket/xwb/demo/movielens/1m/rank/test.parquet

## model configurations
din_column_name_path: s3://dmetasoul-bucket/xwb/demo/movielens/1m/rank/column_schema_DIN.txt
din_combine_schema_path: s3://dmetasoul-bucket/xwb/demo/movielens/1m/rank/combine_column_schema_DIN.txt
wide_column_name_path: s3://dmetasoul-bucket/xwb/demo/movielens/1m/rank/column_schema_DIN.txt
wide_combine_schema_path: s3://dmetasoul-bucket/xwb/demo/movielens/1m/rank/combine_column_schema_wide.txt
deep_column_name_path: s3://dmetasoul-bucket/xwb/demo/movielens/1m/rank/column_schema_DIN.txt
deep_combine_schema_path: s3://dmetasoul-bucket/xwb/demo/movielens/1m/rank/combine_column_schema_deep.txt

model_in_path: null
model_out_path: s3://dmetasoul-bucket/demo/movielens/model/din/model_out/ml_1m/
## model_export_path: s3://dmetasoul-bucket/demo/movielens/model/din/model_export/ml_1m/
model_version: '0.1'
experiment_name: movie_lens_din_1m
input_label_column_index: 0
metric_update_interval: 100

## model hyper params
use_wide: True
use_deep: True
din_embedding_dim: 16
wide_embedding_dim: 16
deep_embedding_dim: 16
din_attention_hidden_layers: [16, 8]
din_attention_hidden_activations: dice
din_attention_batch_norm: True
din_attention_dropout: 0.0
din_hidden_layers: [32, 16]
din_hidden_activations: dice
din_hidden_batch_norm: True
din_hidden_dropout: 0.0
seq_column_index_list: [1, 3]
target_column_index_list: [2, 4]
deep_hidden_units: [32, 16]
deep_hidden_activations: ReLU
deep_hidden_dropout: 0.0
deep_hidden_batch_norm: True
sparse_init_var: 0.01
ftrl_l1: 1.0
ftrl_l2: 120.0
ftrl_alpha: 0.5
ftrl_beta: 1.0