apiVersion: v1
kind: Service
metadata:
  name: {{ include "serving-chart.fullname" . }}
  labels:
    {{- include "serving-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    #设置gRPC端口
    - name: grpc
      port: {{ .Values.serving.port }}
      targetPort: {{ .Values.serving.port }}
  selector:
    {{- include "serving-chart.selectorLabels" . | nindent 4 }}
