apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "serving-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "serving-chart.name" . }}
    helm.sh/chart: {{ include "serving-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "serving-chart.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "serving-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .Values.storageclass }}
      labels:
        app.kubernetes.io/name: {{ include "serving-chart.name" . }}
        helm.sh/chart: {{ include "serving-chart.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        # Revision should change with each helm upgrade, so if we use it here
        # and don't specify spec.selector, we run into https://github.com/helm/charts/issues/7726
        revision: {{ .Release.Revision | quote }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "serving-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/opt/metaspore-serving/bin/metaspore-serving-bin","-grpc_listen_port","{{ .Values.serving.port }}"]
          ports:
            - name: grpc
              containerPort: {{ .Values.serving.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}