apiVersion: metaspore/v1
kind: OfflineLocalFlow
metadata:
  name: offline_local_flow
spec:
  # offlineLocalImage: 'swr.cn-southwest-2.myhuaweicloud.com/dmetasoul-repo/metaspore-training-release:v1.0.6'
  offlineLocalImage: 'metaspore-training-release-xhd-test:latest'
  offlineLocalContainerName: 'metaspore_offline_flow'