apiVersion: metaspore/v1
kind: TrainingJob
metadata:
  name: ItemCF
  category: Match/I2I/Swing

spec:
  logging:
    loglevel: debug
  
  spark:
    session_confs:
      app_name: 'Ecommerce Swing I2I Pipeline'
      local: True
      worker_count: 1
      worker_cpu: 2
      server_count: 1
      server_cpu: 2
      batch_size: 128
      worker_memory: '4G'
      server_memory: '4G'
      coordinator_memory: '2G'
    extended_confs:
      spark.network.timeout: '500'
      spark.ui.showConsoleProgress: 'true'
      spark.kubernetes.executor.deleteOnTermination: 'true'
      spark.jars.packages: 'org.mongodb.spark:mongo-spark-connector_2.12:3.0.1'
  
  dataset:
    train_path: /opt/volumes/output/data/match/icf/train.parquet
    test_path: /opt/volumes/output/data/match/icf/test.parquet
    fmt: parquet

  training:
    i2i_estimator_class: metaspore.algos.item_cf_retrieval.ItemCFEstimator
    i2i_estimator_config_class: metaspore.algos.pipeline.ItemCFEstimatorConfig
    # i2i_estimator_class: metaspore.SwingEstimator
    # i2i_estimator_config_class: metaspore.algos.pipeline.SwingEstimatorConfig
    estimator_params:
      max_recommendation_count: 20
  
  mongodb:
    uri: mongodb://root:test_mongodb_123456@localhost:27018/?authSource=admin
    database: jpa
    write_mode: overwrite
    index_fields: []
    index_unique: False
    collection: amazonfashion_swing

